using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Ship : MonoBehaviour

{ 
    private float speed = 25.0f;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKey(KeyCode.LeftArrow))
        {
            transform.position += Vector3.left * speed * Time.deltaTime;
        }
        if (Input.GetKey(KeyCode.RightArrow))
        {
            transform.position += Vector3.right * speed * Time.deltaTime;
        }
       if (Input.GetKey(KeyCode.Space))
        {

        }
    }
}
